// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lecesunfdmpfabhizcvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlY2VzdW5mZG1wZmFiaGl6Y3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mzg2NTQsImV4cCI6MjA3MTExNDY1NH0.jU4XFRNkyOhKZk40t9592hqikVaL9URt2p1OZ0OrQ_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});